language: go

go:
  - 1.2
  - 1.3
  - tip

install: script/bootstrap

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - script/lint
  - script/coverage --coveralls

branches:
  only:
    - master

matrix:
  allow_failures:
    - go: tip
